name: Update gist with WakaTime stats
on:
  schedule:
    - cron: '59 23 * * 0-6'
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: FanchiniRudolf/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: b484c7d652273aae73462bc35bcda1f1
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
